version: "3"

services:
  app:
    image: node:16
    command: tail -f /dev/null
    volumes:
      - .:/workspace
      - node_modules:/workspace/node_modules
    working_dir: /workspace

volumes:
  node_modules:
